
// This file was auto-generated by ML.NET Model Builder. 

using MLModel1_ConsoleApp1;
while (true)
{
    Console.WriteLine("Start to predict");
    // Create single instance of sample data from first line of dataset for model input
    MLModel1.ModelInput sampleData = new MLModel1.ModelInput()
    {
        Message = Console.ReadLine(),
    };



    Console.WriteLine("Using model to make single prediction -- Comparing actual IsToxic with predicted IsToxic from sample data...\n\n");


    //Console.WriteLine($"Message: {@"Mọi người chia sẻ môn .NET!"}");
    //Console.WriteLine($"IsToxic: {0F}");


    var sortedScoresWithLabel = MLModel1.PredictAllLabels(sampleData);
    Console.WriteLine($"{"Class",-40}{"Score",-20}");
    Console.WriteLine($"{"-----",-40}{"-----",-20}");

    foreach (var score in sortedScoresWithLabel)
    {
        Console.WriteLine($"{score.Key,-40}{score.Value,-20}");
    }

    Console.WriteLine("=============== End of process, hit any key to finish ===============");
    Console.ReadKey();
}
